from __future__ import annotations

from typing import Any

from workload_intelligence.exporters.elastic_constants import (
    INDEX_AGGREGATE_WINDOWS,
    INDEX_LINEAGE_EVENTS,
    INDEX_LINEAGE_RECOMMENDATIONS,
    INDEX_LINEAGE_TEMPLATES,
    INDEX_LINEAGE_VALIDATION,
    INDEX_PRIMITIVE_EVENTS,
    INDEX_PRIMITIVE_SIGNALS,
    INDEX_PROFILES,
    INDEX_RECOMMENDATIONS,
    INDEX_SIM_RUNS,
)


def index_templates() -> dict[str, dict[str, Any]]:
    keyword = {"type": "keyword"}
    date = {"type": "date"}
    double = {"type": "double"}
    integer = {"type": "integer"}
    flattened = {"type": "flattened"}
    text = {"type": "text"}
    condition = {
        "type": "nested",
        "properties": {
            "path": keyword,
            "operator": keyword,
            "threshold": keyword,
            "threshold_number": double,
            "observed_value": {"type": "keyword"},
            "observed_number": double,
            "passed": {"type": "boolean"},
        },
    }
    source_number = {
        "type": "nested",
        "properties": {"path": keyword, "value": double},
    }
    matched_primitive = {
        "type": "nested",
        "properties": {
            "primitive": keyword,
            "signal_weight": double,
            "rule_confidence": double,
            "rule_ids": keyword,
            "evidence": text,
        },
    }
    common = {
        "run_id": keyword,
        "scenario_name": keyword,
        "seed": integer,
        "system_id": keyword,
        "customer_id": keyword,
        "platform": keyword,
        "database_or_index": keyword,
    }
    return {
        INDEX_SIM_RUNS: {
            "generated_at": date,
            "event_count": integer,
            "validation_status": keyword,
            "validation_warning_count": integer,
            "artifact_path": keyword,
            "time_range": flattened,
            **common,
        },
        INDEX_PRIMITIVE_EVENTS: {
            "event_id": keyword,
            "timestamp": date,
            "template_id": keyword,
            "database_or_index": keyword,
            "latency_ms": double,
            "response_bytes": double,
            "result_count": double,
            "command": keyword,
            "endpoint": keyword,
            "method": keyword,
            "normalized_query": flattened,
            "normalized_query_text": text,
            "normalized_query_command": keyword,
            "raw_query_body": flattened,
            "raw_query_text": text,
            "primitive_signals": flattened,
            **common,
        },
        INDEX_PRIMITIVE_SIGNALS: {
            "event_id": keyword,
            "timestamp": date,
            "template_id": keyword,
            "primitive": keyword,
            "signal_weight": double,
            "rule_confidence": double,
            "evidence": text,
            "rule_ids": keyword,
            **common,
        },
        INDEX_AGGREGATE_WINDOWS: {
            "aggregate_window_id": keyword,
            "aggregation_view": keyword,
            "window_start": date,
            "window_end": date,
            "scope_key": flattened,
            "volume_metrics": flattened,
            "latency_metrics": flattened,
            "data_metrics": flattened,
            "primitive_profile": flattened,
            "primitive_profiles": flattened,
            "template_metrics": flattened,
            "top_templates": flattened,
            **common,
        },
        INDEX_PROFILES: {
            "profile_id": keyword,
            "aggregate_window_id": keyword,
            "window_start": date,
            "window_end": date,
            "scope": flattened,
            "volume": flattened,
            "latency": flattened,
            "primitive_profile": flattened,
            "primitive_profiles": flattened,
            "access_pattern_scores": flattened,
            "dominant_patterns": flattened,
            "evidence": flattened,
            **common,
        },
        INDEX_RECOMMENDATIONS: {
            "recommendation_id": keyword,
            "profile_id": keyword,
            "aggregate_window_id": keyword,
            "window_start": date,
            "window_end": date,
            "type": keyword,
            "recommendation": text,
            "target_technology": text,
            "severity": keyword,
            "confidence": double,
            "matched_rule_id": keyword,
            "rule_conditions": condition,
            "evidence": text,
            "recommendation_index": integer,
            **common,
        },
        INDEX_LINEAGE_RECOMMENDATIONS: {
            "recommendation_id": keyword,
            "profile_id": keyword,
            "aggregate_window_id": keyword,
            "window_start": date,
            "window_end": date,
            "matched_rule_id": keyword,
            "recommendation": text,
            "type": keyword,
            "severity": keyword,
            "confidence": double,
            "target_technology": text,
            "rule_conditions": condition,
            "rule_condition_summary": text,
            "source_numbers": source_number,
            "top_template_ids": keyword,
            "sample_event_ids": keyword,
            "evidence": text,
            **common,
        },
        INDEX_LINEAGE_TEMPLATES: {
            "profile_id": keyword,
            "aggregate_window_id": keyword,
            "template_id": keyword,
            "request_count": integer,
            "contribution": double,
            "primitive_summary": flattened,
            "matched_primitives": keyword,
            "matched_rule_ids": keyword,
            "sample_event_ids": keyword,
            "normalized_query": flattened,
            "normalized_query_text": text,
            "normalized_query_command": keyword,
            "raw_query_body": flattened,
            "raw_query_text": text,
            "raw_query_samples": text,
            **common,
        },
        INDEX_LINEAGE_EVENTS: {
            "event_id": keyword,
            "timestamp": date,
            "template_id": keyword,
            "aggregate_window_ids": keyword,
            "profile_id": keyword,
            "recommendation_ids": keyword,
            "latency_ms": double,
            "response_bytes": double,
            "result_count": double,
            "matched_primitives": matched_primitive,
            "normalized_query": flattened,
            "normalized_query_text": text,
            "normalized_query_command": keyword,
            "raw_query_body": flattened,
            "raw_query_text": text,
            **common,
        },
        INDEX_LINEAGE_VALIDATION: {
            "validation_status": keyword,
            "validation_warnings": {"type": "nested", "dynamic": True},
            "expected_primitive_share": flattened,
            "observed_primitive_share": flattened,
            "observed_primitive_profile": flattened,
            "observed_access_pattern_scores": flattened,
            "dominant_patterns": {"type": "nested", "dynamic": True},
            "recommendation_ids": keyword,
            **common,
        },
    }
